[app_config]
host='localhost'
port=5002

[postgres]
host='localhost'
port=5432
username='postgres'
password='password'
database='mercury'

[logging_config]
sqlx_log_level='info'
actix_web_log_level='info'
